site_name: Teste WeHostVoIP Docs

theme:
    name: readthedocs
    locale: en
    navigation_depth: 1

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - meta
  - md_in_html
  - admonition

plugins:
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
